package com.eecs341.greeklife.HouseOf;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/houseOf") // This means URL's start with /demo (after Application path)
public class HouseOfController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private HouseOfRepository houseRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewChapter (@RequestBody HouseOf h) {
		houseRepository.save(h);
		return "Saved";
	}
}
